
services:
    postgres:
        image: postgres:12.17
        container_name: ${POSTGRES_HOST}
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "5432:5432"
        volumes:
            - postgre_docker_vol:/var/lib/postgresql/data
        networks:
            - kubenews_net


    kube_news:
        image: lucas9625/kube-news:${KUBE_TAG:-latest}
        build:
            context: .
            dockerfile: Dockerfile

        container_name: kube_news
        ports:
            - "8080:8080"
        networks:
            - kubenews_net
        depends_on:
            - postgres
        environment:
            DB_USER: ${POSTGRES_USER}
            DB_PASSWORD: ${POSTGRES_PASSWORD}
            DB_DATABASE: ${POSTGRES_DB}
            DB_HOST: ${POSTGRES_HOST:-postgres}



volumes:
    postgre_docker_vol:
        name: postgre_docker_vol
        #usado para usar um volume externo
        external: true
networks:
    kubenews_net:
        name: kubenews_net 
        #usado para usar uma network externa
        #external: true
        driver: bridge
